### ISSUE TITLE
Cannot delete entity instance. Another entity istance depends on it.

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/cloud-mdk-samples#15]
Dears, 

I'm having an issue to delete an entity created with "CreateLinks".
I've made the createEntity action as the following:
![image](https://user-images.githubusercontent.com/18472559/136428563-2da948d1-9159-4354-9ebd-3a48648ff5d0.png)
This works good and i can made some expands, for example, with offline storage.

I've created an entity to delete those entities:
![image](https://user-images.githubusercontent.com/18472559/136428936-4fc695df-4b16-465b-9d5c-870b7f109a98.png)

But when I try to delete the entity with an DeleteEntity action, I'm getting an error with "**Cannot delete this entity instance. Another entity instance depends on it**".
How can I solve this issue?

**Comment by jitendrakansal** [comment]
[MiqueiasMaia](https://github.com/MiqueiasMaia) do you still have this issue? Please close it if it has been resolved.
