### ISSUE TITLE
[CAP/MDK] - How to make a media entity like "Products" from show case app "ImageHandling" on CAP?

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/cloud-mdk-samples#16]
Hello experts. My issue it's with CAP and MDK to handle images.

We've implemented an entity on CAP (exposing the service as OData v2) as the following example to save media (using CreateMediaAction) and download them (using DownloadMediaAction). We can save the media on Hana instance with a column to save the binaries, like show on screenshot.

`entity Medias {
    key ID : UUID;
    swp: Association to SafeWorkPermissions;
    @Core.MediaType: mediaType
    content : LargeBinary;
    @Core.IsMediaType: true
    mediaType : String default 'image/jpeg';
}
`

![image](https://user-images.githubusercontent.com/18472559/141156727-8e5ca06c-e8f4-473d-b744-2fde0278e5f8.png)

We have made as the example in show case apps to handle images, but our response data isn't equal as the data from example app, as we show here:
Response and response data from our service (the values are separated by 'e'):
![image](https://user-images.githubusercontent.com/18472559/141157799-abacd057-362e-4033-b6d4-d9ab18fb473e.png)

Response and response data from SampleServiceV2 from showcase app (the values are separated by 'e'):
![image](https://user-images.githubusercontent.com/18472559/141158765-8a6427ff-aec7-432b-9cc4-d10d8f034424.png)

I think we haven't define the entity as the entity Product from SampleServiceV2.
Could somebody explain?

**Comment by billfroelich** [comment]
​I would recommend you check out the [​CAP documentation](https://cap.cloud.sap/docs/guides/) and there is also the ​[cloud-cap-samples git repo ​media](https://github.com/SAP-samples/cloud-cap-samples/tree/main/media) sample service you can look at as well.  If you still have questions you might be better asking against the cap projects.

**Comment by MiqueiasMaia** [comment]
Thanks for ur answear @billfroelich. We'll check those examples.
