### ISSUE TITLE
Error while Deploying PDFGenerationApp

### ISSUE THREAD

**Issue by JOSEPHSASIKANTHREDDY** [SAP-samples/cloud-mdk-samples#19]
Hi,
As mentioned in the Readme file.
I've imported the PDFGenerationApp and tried to deploy but facing the below error related to the pdfmake.

![image](https://user-images.githubusercontent.com/8137364/144634455-e72b06b5-b59a-4b26-b561-67920e07424e.png)

Please help me to solve the issue.

With Regards,
Joseph.

**Comment by billfroelich** [comment]
Did you update your external references in BAS?

From the PDFGenApp/README.md

If you are using SAP Business Application Studio or Visual Studio Code to develop your app, then you need to add "pdfmake/build/pdfmake" to the externals property of the built-in MDK bundler tool.

Go to Preferences > Search for "MDK Bundler Externals" > Press Edit in settings.son > Add "pdfmake/build/pdfmake" inside the "mdk.bundlerExternals" array. e.g.

"mdk.bundlerExternals": [
 "pdfmake/build/pdfmake"
]

**Comment by JOSEPHSASIKANTHREDDY** [comment]
Hi,
Where can I find Preferences> option.
Is it related to Application or BAS editor?

Thanks.

**Comment by billfroelich** [comment]
Use the gear icon in the lower left in BAS and select "Open Preferences" to display the preferences page.  Once open, navigation to the Extensions > Mdk section and under Bunder Externals click the "Edit in settings.json" link.

**Comment by JOSEPHSASIKANTHREDDY** [comment]
Thanks,I found out.
