### ISSUE TITLE
Retrieve local storage after logout and login again

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/cloud-mdk-samples#22]
Hey Experts.

There exists any way to retrieve local storage after app logout and provide login again?
When I do this process, the app data isn't there.

**Comment by billfroelich** [comment]
Can you clarify what you want you mean by local storage?  Normally the user would just swipe closed the app and re-launch.  If passcode is enabled then they will enter their passcode and the app will launch again.

The logout function is more of a reset that clears any offline data and resets back to the welcome page to start again.

**Comment by MiqueiasMaia** [comment]
Hello @billfroelich. As local storage I want mean offline data, like data that wasn't sync with the database.

**Comment by MiqueiasMaia** [comment]
Dears, I'm reopening this discussion because, in our development requirements, our client requires a feature similar to a "black box" (yes, like the airplanes lol), with the possibility of recovering the data if the user did the logout, saving all data before the logoff in another database or dump file.

Could you help me with any ideas?

**Comment by billfroelich** [comment]
No matter what you do, if the user deletes the app from their device without syncing data it will be lost.  A reset (logout action with SkipReset false) will automatically delete all offline db files and clear the client removing all user data.

From my perspective the best option would be to add a check when the user clicks the logout button to force the sync if there are local changes.  If there are local changes don't allow the logout to proceed until the changes are sync'd.  When you get into trying to save off databases the security / encryption become more problematic and not worth it if not impossible.

**Comment by jitendrakansal** [comment]
@MiqueiasMaia Is this still an open issue? If not, can it be closed?
