### ISSUE TITLE
Reg. Calendar Control undefined error

### ISSUE THREAD

**Issue by mgrvinoth90** [SAP-samples/cloud-mdk-samples#35]
Hi Team,
 
I would like your support to resolve the following issue while implementing the Calendar Control.
 
In one of the SAP Asset Manager project, we tried to implement the Calendar Control as an Extension control ( from MDK showcase apps ) and it’s working fine, once we try to launch the app from VSCode and Xcode.
 
 
Calendar Page from our application (Launched from VSCode/Xcode) - Refer attachment
 
 
At the same time, if we prepare the installer (archived and prepared iPa) and test it from device by installing it, we are facing the below error.
 
Calendar control gives the below error (once it’s installed and launched) - Refer attachment
 

 
[FUICalendarViewControllerBridge_Error.docx](https://github.com/SAP-samples/cloud-mdk-samples/files/11724797/FUICalendarViewControllerBridge_Error.docx)

 
 
Could you provide your suggestion to resolve this issue?
 
For your information,
 
We are using MDK 6.3.3 version and SSAM 2210.
 
Note: We are facing the same problem, even if we try to replicate the steps for Calendar Showcase app.

**Comment by billfroelich** [comment]
I would suggest updating to MDK 23.4.1.  I just cloned the repo, built the client using create-client and then created and enterprise ipa file from XCode 14.3.1 with MDK 23.4.1.  I installed the ipa on my iPad Pro 11" and onboarded.  I see the calendar as expected on my device and I also launched it into a simulator and see the calendar there as expected as well.
This was all using the Showcase app as is without modifications.

**Comment by mgrvinoth90** [comment]
Hi Bill,

Thanks for your response!

Could you confirm, whether the same app is working fine with MDK SDK 6.3.8?

Since, we integrated this app in SAP SSAM 2210 application and we are currently using MDK SDK 6.3.3. If you confirm, the app is working fine with 6.3.8., then we will upgrade to 6.3.8 and test.

Thanks!

**Comment by billfroelich** [comment]
I tested with 6.3.9 and it worked as expected.
